name: CD

on:
  push:
    branches:
    - master
    tags:
    - v*
  pull_request:
    branches:
      - master

jobs:

  Prepare:
    name: Prepare for builds
    runs-on: ubuntu-16.04
    steps:
    - name: Create commit-sha file
      env:
        GITHUB_SHA: ${{ github.sha }}
      run: |
          echo $GITHUB_SHA > commit-sha
    - name: Publish commit-sha
      uses: actions/upload-artifact@v2
      with:
        path: commit-sha
        name: dist

    Release:
    needs: Prepare
    runs-on: ubuntu-16.04
    if: success()  # and github.event_name == 'tag'
    steps:
    - uses: actions/checkout@v2
    - name: Download assets
      uses: actions/download-artifact@v1.0.0
      with:
        name: dist
    - name: Create release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # provided by Actions
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
            Autogenerated binary modules.
        draft: false
        prerelease: false
    - name: Upload Release Assets
      uses: AButler/upload-release-assets@v2.0
      with:
        release-tag: ${{ github.ref }}
        files: 'dist/*.zip;dist/commit-sha'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
